# Generated by Django 4.1.3 on 2022-11-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaDepot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Popular'), (3, 'Promo')], default=1),
        ),
    ]
