# Generated by Django 4.1.3 on 2022-11-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaDepot', '0002_articulo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50)),
                ('NombreArticulo', models.CharField(max_length=50)),
                ('Precio', models.FloatField()),
                ('Cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
